name: Release

on:
  push:
    branches:
      - dev
    paths:
      - ".changeset/**"
      - ".github/workflows/release.yml"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: ${{ github.repository_owner == 'tiesen243' }}
    name: Create a PR for release workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install NPM Dependencies
        run: bun ci

      - name: Create Version PR
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: bun .github/scripts/changeset-version.js
          publish: bun run changeset tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
